//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulletinBoardFrameModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.posts = new HashSet<post>();
            this.posts1 = new HashSet<post>();
            this.users1 = new HashSet<user>();
            this.users11 = new HashSet<user>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string profile { get; set; }
        public string type { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public int create_user_id { get; set; }
        public int updated_user_id { get; set; }
        public Nullable<int> deleted_user_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual ICollection<post> posts { get; set; }
        public virtual ICollection<post> posts1 { get; set; }
        public virtual ICollection<user> users1 { get; set; }
        public virtual user user1 { get; set; }
        public virtual ICollection<user> users11 { get; set; }
        public virtual user user2 { get; set; }
    }
}
